### ISSUE TITLE
Save key eligibility criteria selections for all benefits

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/usagov-benefits-eligibility#157]
As a BEARS site user, in order to avoid repetitive tasks and browse benefits efficiently, I would like key eligibility criteria selections to be saved from one benefit to others.

Pre-conditions:

- [x] User story allowing users to select key eligibility criteria in the benefits cards is done (#158 )

Acceptance Criteria:

- [x] Key eligibility criteria that the user selected on one benefit card are also selected on all other benefit cards

Definition of Done:
- [x] Code complete
- [x] Security scans passed
- [x] QA tested
- [x] Accessibility tested
- [x] Deployed to staging
- [x] PR approved / Peer reviewed
- [x] PO approved

[BEARS P4 Definition of Done](https://docs.google.com/document/d/118sdf54uF1vz-5pMvGodV8LRnrUJfjMbHcarCA8AS70/edit)

**Comment by r-bartlett-gsa** [comment]
@fpigeonjr Here's my initial feedback for both stories, 157 and 158:

Current: 'Not applicable' option for radio fields is not displayed within the benefit card
Suggestion: Add 'not applicable' option to radio fields within the benefit card

Current: after selecting a criteria within the benefit card, the card collapses and moves out of the viewing area. 
Suggestion: after selecting a criteria within the benefit card, the card should remain open and auto scroll with the re-sort.

Current: Met checkbox criteria does not change font color
Suggested: Met checkbox criteria should display in green font

Current: Virtual criteria (criteria that is in the benefit card and not in the left-hand rail filters) is not counted in eligibility calculation. See https://www.screencast.com/t/QNG1mV79
Suggestion: If virtual criteria is selected within the benefit card, it should behave (calculate) the same as any other selected criteria.

Current: If the field is select type, selecting 'select' option disqualifies
Suggestion: Selecting 'select' option should be an 'unknown' state, based on which estimation is not calculated. (different than radio type, selecting 'not applicable' is a 'no' state)

Current: The spacing between questions on the left-hand rail is not sufficient
Suggestion: Add top and/or bottom margins to the radio/select fields. See: https://www.screencast.com/t/CN9VPLs7
Maybe: increase font weight of questions, but not options, and change the color of H2s within the left-hand rail to blue (#154285).

**Comment by r-bartlett-gsa** [comment]
I got the link from Federalist: https://federalist-edd11e6f-8be2-4dc2-a85e-1782e0bcb08e.app.cloud.gov/preview/gsa/usagov-benefits-eligibility/benefit-card-feedback/ (that's the one, right?)
And here's some of my comments/questions (I'll add it to GH too for the record):

- I like the font weight/h2 color change. But I still think we should increase the top/bottom margin for radio button questions.
- Should we move the 'not applicable' option to the bottom? The questions just don't read right when the first option is 'not applicable'.
- There's something wonky going on with age criteria selection and it's inconsistent. So perhaps we can zoom sometime tomorrow so I can show you. It also could be that these fields don't have accepted values assigned to them, they are just labels, and it's an issue that will get resolved ones date field type is implemented.

**Comment by fpigeonjr** [comment]
@r-bartlett-gsa ,
1. Do you mean the margin in between the  questions in the left-rail?
2. Sure, we can move the na option to the bottom. Follows more of the common convention.
3. Yes I believe you're right in the `benefit.md` will need an acceptable value set to `true` for it to work. We can zoom today or talk about it at stand up today.
<img width="929" alt="Screen Shot 2022-02-23 at 7 48 31 AM" src="https://user-images.githubusercontent.com/4629398/155333704-b6af75e3-e486-497e-b880-cbcb36604389.png">

**Comment by fpigeonjr** [comment]
🚀 @r-bartlett-gsa [preview link](https://federalist-edd11e6f-8be2-4dc2-a85e-1782e0bcb08e.app.cloud.gov/preview/gsa/usagov-benefits-eligibility/benefit-card-feedback/) is ready!

**Comment by maomeara63** [comment]
@r-bartlett-gsa @fpigeonjr 

1. Persistence of selections

- It appears that selecting criteria on a card selects the identical criteria on all the cards within that life event and in the associated filter (where appropriate). That works.

- However, the selection doesn't carry over to other life events.

- Going back to the home page appears to erase all selections. (I understand that this might be the desired behavior, but if a user enters a bunch of criteria and then goes back to look at other life events and re-enters the same life even, I might expect my selections to persist. That might not be a reasonable expectation.)

2. Dropdown for relationship to deceased. I'm wondering why all the other dropdowns were changed to radio buttons but the relationship with deceased were changed to radio buttons. Is this intentional? 

3. I think we should see if there is a negative state for the dropdown that communicates more information to the user.

![Dropdown negative state](https://user-images.githubusercontent.com/65717217/156178504-6785988b-638c-4004-b4f6-93a66cdb065a.JPG)

**Comment by maomeara63** [comment]
@r-bartlett-gsa 
1. Cool
2. Makes sense
3. I'm not sure. Maybe you and I can brainstorm on this.
