### ISSUE TITLE
Fix code scanning alert - High severity - Regular Expression Denial of Service (ReDoS) vulnerability in nth-check

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA/usagov-benefits-eligibility#316]
Tracking issue for:
- [ ] https://github.com/GSA/usagov-benefits-eligibility/security/code-scanning/8

**Comment by lgarceau768** [comment]
Closed the [issue](https://github.com/GSA/usagov-benefits-eligibility/security/code-scanning/8) due to the fact that this vulnerability is a heavily nested devDependency within the latest version of `nuxt`. Also a ReDoS vulnerability will not have an effect on a user of a static generated content site and will only effect the attacker as no data is saved from client interactions.
