### ISSUE TITLE
Verify that the test suite fails when errors are detected

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA/usagov-benefits-eligibility#426]
# User Story

As a BEARS **operator**, in order to **prevent broken code from being deployed**, I would like **the test suite to fail when errors are detected** .

Acceptance Criteria:

- [ ] when an error message is generated (such as the three listed in #425), `npm test` should fail with a non-zero result code

Definition of Done:

- [ ] Code complete
- [ ] Tests coverage is greater than team benchmark (90% goal)
- [ ] Security scans passed
- [ ] Acceptance Criteria is met and it works as expected
- [ ] Accessibility tested
- [ ] Build process and deployment is automated and repeatable
- [ ] Load testing/performance testing
- [ ] Self Documentation whenever possible
- [ ] Feature toggles if appropriate
- [ ] Deployed to staging
- [ ] Usability testing
- [ ] PR approved / Peer reviewed
- [ ] PO approved

**Comment by lgarceau768** [comment]
I am fairly certain that it does correctly, I think that the errors listed in #425 are mainly `Vue Warn`(ings) which since we are using `vue test-utils` which wraps over jest I think that is why it  does not cause `npm run test` to fail. I think that this is alright due to the program still failing when there is critically breaking logic
<img width="749" alt="Screen Shot 2022-05-19 at 4 06 03 PM" src="https://user-images.githubusercontent.com/51423366/169395890-830af2cd-1640-4750-a8f1-d78cc1ee34fe.png">

I will do some more research into this but I think as long as developers in the future just fix any vue warnings that appear in the output, it should be sufficient.
