### ISSUE TITLE
[on hold][bug] Survivor Benefits for Spouse criteria can never be met

### ISSUE THREAD

**Issue by danny-englander** [GSA/usagov-benefits-eligibility#603]
# User Story

As a BEARS site visitor, in order to fulfill all 6 criteria for `Survivor Benefits for Spouse`, I would like to see the `If divorced, your marriage lasted at least 10 years.` checkbox in the left sidebar under `About you (the person applying for benefits)`

Steps to reproduce

- [ ] Go to BEARS main page
- [ ] expand the accordion item called`Survivor Benefits for Spouse`
- [ ] observe the checkmarks in the accordion content as you fill out form items in the sidebar
- [ ] Enter a birthday of 01/01/1963 or any birthdate that would make you at least 60 years old
- [ ] For `Your relationship to the person who died is`, enter "spouse"
- [ ] Under `About the person who died`, check the box called `The deceased worked and paid Social Security taxes on their earnings.`
- [ ] Now under `About you (the person applying for benefits)`, check the box called `You are a U.S. citizen or eligible non-citizen.`
- [ ] under the same area, select `Your marital status is divorced`
- [ ] Now in observe in the accordion content area, you will see `Key eligibility criteria (You must meet all criteria. You currently meet 5 of 6).`
- [ ] It is at this point that the 6th criteria item can never be met, `If divorced, your marriage lasted at least 10 years.` because that checkbox is missing under `About you (the person applying for benefits)`

Acceptance Criteria:

- [ ] You will be able to satisfy the above criteria in `Steps to reproduce` once the bug is fixed

Proposed Fix:
- [ ] Add `applicant_marriage_length` key to `content/life-events/death-of-a-loved-one.md` under `criteriaKeys`

Definition of Done:

- [ ] Code complete
- [ ] Tests coverage is greater than team benchmark (90% goal)
- [ ] Security scans passed
- [ ] Acceptance Criteria is met and it works as expected
- [ ] Accessibility tested
- [ ] Build process and deployment is automated and repeatable
- [ ] Load testing/performance testing
- [ ] Self Documentation whenever possible
- [ ] Feature toggles if appropriate
- [ ] Deployed to staging
- [ ] Usability testing
- [ ] PR approved / Peer reviewed
- [ ] PO approved

**Comment by r-bartlett-gsa** [comment]
@danny-englander @gchi25 This is actually an intentional design. Some criteria are considered "virtual criteria". Per our [content management documentation](https://docs.google.com/document/d/1diFkssr7YeRXdresLuLc6WdtHULy4RceCSzYLgmLcwE/edit?usp=sharing):

> The criteria that is assigned to the benefit but not to the life event that the benefit belongs to is called virtual criteria. The user cannot interact with virtual criteria and it is not used in the logic to re-sort the benefits based on relevance.

The intend is avoid overwhelming the user with too many questions, specifically when the question only satisfied eligibility for one or two benefits within a life event. We tried to find the balance between asking just the right amount of eligibility questions and the benefit results accuracy. You can find more benefit with other virtual criteria, for example Dependency and Indemnity Compensation (DIC) for Parent, with a virtual criteria "You have limited income and resources". I'm happy to discuss this in more detail, please let me know.

**Comment by danny-englander** [comment]
@r-bartlett-gsa ok fair enough, thanks for the explanation. No further followup required.
