### ISSUE TITLE
Potentially add cSpell spell checker as a GitHub action

### ISSUE THREAD

**Issue by diegocob** [GSA/usagov-benefits-eligibility#693]
### Description

Adding "automated spelling to GitHub actions using cSpell."

**Comment by FatmaBakir** [comment]
I've implemented the `cSpell Github Actions`. It is spell checking both `locales` and `content` folders where Diego is mainly working in (We can change the location being scanned if needed) and reporting error messages if it detects errors either in English or Spanish. So, working as expected!

It's currently failing because there are some errors detected. There were some words like "covid, USAGOV" that I know should be ignored and I added those to the `cSpell.json` `words` list so that they are ignored going forward. So, if there are other words need to be ignored, please let me know. 

You may see one example job run report at this link, under Run cSpell section:
https://github.com/GSA/usagov-benefits-eligibility/actions/runs/4381359533/jobs/7669359182

I assume some of those typos cannot be corrected as they are part of the code. 

It's all ready for implementation. I need your direction/approval to create a PR. 

Please let me know how you'd like to proceed. @erniedeeb @diegocob @danny-englander

**Comment by diegocob** [comment]
Thanks, Fatma.

Suggesting a time for us to talk and see how to scan existing and future
content.

Best,
