### ISSUE TITLE
Update all navigation Links after beta.usa.gov goes live

### ISSUE THREAD

**Issue by danny-englander** [GSA/usagov-benefits-eligibility#711]
### Description

Once beta.usa.gov goes live to usa.gov, we will need to update any navigation links to usa.gov

### User Story
As a developer, I need to update the header and footer navigation links to the new live links once beta.usa.gov goes live to usa.gov

**Comment by danny-englander** [comment]
@nehemiah-abuga This is ready for testing

## Header 

- [ ] 1. Pull multi-life-event-2023 to your local
- [ ] 2. run npm i
- [ ] 3. Run npm run dev
- [ ] 4. Go to http://localhost:3000/
- [ ] 5. Inspect the main navigation and ensure that the link text and links match what is on https://www.usa.gov/
- [ ] 6. Switch language to Spanish
- [ ] 7. Inspect the main navigation and ensure that the link text and links match what is on https://www.usa.gov/es

### Footer

- [ ] Pull `multi-life-event-2023` to your local
- [ ] run `npm i`
- [ ] Run `npm run dev`
- [ ] Go to http://localhost:3000
- [ ] Inspect the footer navigation and ensure that the link text and links match what is on https://beta.usa.gov/
- [ ] Switch language to Spanish
- [ ] Inspect the footer navigation and ensure that the link text and links match what is on https://beta.usa.gov/es

**Comment by nehemiah-abuga** [comment]
I have validate the changes and everything looks good

**Comment by amycole501** [comment]
I can't test this since I don't have the localhost access set up. Is there any other way to test it? @danny-englander

**Comment by danny-englander** [comment]
Amy, the html has not changed only the links but if you'd like to test

## Header 

- [ ] Go to https://federalist-edd11e6f-8be2-4dc2-a85e-1782e0bcb08e.sites.pages.cloud.gov/preview/gsa/usagov-benefits-eligibility/multi-life-event-2023/death-of-a-loved-one/
- [ ] Inspect the main navigation and ensure that the link text and links match what is on https://www.usa.gov/
- [ ] Switch language to Spanish
- [ ] Inspect the main navigation and ensure that the link text and links match what is on https://www.usa.gov/es

### Footer

- [ ] Go to https://federalist-edd11e6f-8be2-4dc2-a85e-1782e0bcb08e.sites.pages.cloud.gov/preview/gsa/usagov-benefits-eligibility/multi-life-event-2023/death-of-a-loved-one/
- [ ] Inspect the footer navigation and ensure that the link text and links match what is on https://www.usa.gov/
- [ ] Switch language to Spanish
- [ ] Inspect the footer navigation and ensure that the link text and links match what is on https://www.usa.gov/es

**Comment by amycole501** [comment]
**Header:**

- When using a keyboard to tab through the header, the issue of skipping the "call us/search" area is coming up so that interactivity doesn't match USA's live site.
- In JAWS our test link navigation says "primary navigation" which is great; USA's does not. I want to keep ours as-is.
- I don't know why but in the Spanish version of both USA and our test link it says "list with SIX items" and not seven like it does on the English side. After looking at the different versions of the site it appears there are different navigation options in Spanish vs. English. Not sure why that is (??) but thought I'd mention it.
-  The focus indicator color is red on the USA site, it's blue on the test link

**Stuff I think is different because we haven't deployed the changes and aren't using the live site header yet:**
- breadcrumb navigation is missing on the test link but that may be intentional and not able to be reproduced in the draft link. -The "give feedback" CTA is missing but again, probably not available on the test link.
-  The "Here's how you know" information is really different on both sites.  The wording is different. It looks like USA chose to use a different banner area or something. Again, maybe something that'll update once it's on the live site.
- Wildly different mobile navigation visuals (again, maybe due to the different links). Trying to paste a screen shot below. The search is at the top of the USA site, at the bottom of our test link.

![image](https://user-images.githubusercontent.com/117778073/231292317-439dd899-9889-4120-a6cf-1cb0beff920d.png)

FOOTER
USA site doesn't have "return to top" html link, it's moved into a right side "top" tab/callout
Sign Up button is capitalized (both words) on our link, not on the USA site (Sign up)
Missing the "give feedback" CTA stuck to the right side on our link
Very minor difference, but the leading between lines is tighter on the USA footer links than on ours
Make sure the "USAGov is the official..." words are capitalized the same as the USA site's version. Looks like they aren't capitalizing everything like ours is.

in Spanish the two sites appears (and sounded) almost identical. I couldn't find discrepancies with one another.

**Comment by amycole501** [comment]
There's no regression on the update. My comments are improvements and can be broken into separate tickets.
